apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-app-server
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.hostname }}`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: {{ .Values.name }}-service
          port: 8080
---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: productpage-header
#   namespace: bookinfo
# spec:
#   headers:
#     customRequestHeaders:
#       Host: productpage.bookinfo.svc