apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-stable
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-canary
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

