apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  selector:
    app: api
  ports:
  - port: 8080
    protocol: TCP

---
#itsio vsvc
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}-vsvc
spec:
  hosts:
  # - "{{ .Values.name }}-service.backend.svc.cluster.local"
   - "service"
  http:
  - name: primary        # referenced in canary.trafficRouting.istio.virtualService.routes
    route:
    - destination:
        host: {{ .Values.name }}-stable.backend.svc.cluster.local # referenced in canary.stableService
        port:
          number: 8080
      weight: 100
    - destination:
        host: {{ .Values.name }}-canary.backend.svc.cluster.local # referenced in canary.canaryService
        port:
          number: 8080
      weight: 0
---
#TaefikService
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-stable
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-canary
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
